# AdMiner UI: http://localhost:8080
# Engine: PostgreSQL
# Server: db
# User: postgres
# Password: example

version: '3.1'

services:
  db:
    image: postgres:15.3-alpine3.18
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
